spring.application.name=TimeandAttendanceManagement
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# テーブルの自動生成を無効化
spring.jpa.hibernate.ddl-auto=none

# テスト用データベースの設定
spring.sql.init.mode=always
spring.h2.console.enabled=true


# デバッグ用
spring.datasource.url=jdbc:h2:file:./data/sampledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
logging.level.root=INFO
